[package]
name = "bpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
rayon = "1.5.1"
num_cpus = "1.13.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

